services:
  postgres:
    image: postgres:16-alpine
    container_name: my_postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: inventory_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - my-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: my_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: password123
    ports:
      - "8081:80"
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - my-network

volumes:
  postgres_data:

networks:
  my-network:
    driver: bridge
